spring:
  config:
    activate:
      on-profile:
        - docker

  datasource:
    url: jdbc:postgresql://postgres:5432/authentication-service

  data:
    redis:
      host: redis
      port: 6379

  ldap:
    urls: ldap://openldap:389
