spring:
  config:
    activate:
      on-profile:
        - dev

  application:
    name: authentication-service

  datasource:
      url: jdbc:postgresql://localhost:5433/authentication-service
      username: postgres
      password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:database/migration

  data:
    redis:
      host: localhost
      port: 6379

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: 900000
  refreshExpiration: 604800000

server:
  port: 8081